// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAWuxMgU0f8MiXPFLYIWiwdZBBt5cCX3Q',
    appId: '1:79477247464:web:91dda0fa8122207256a85d',
    messagingSenderId: '79477247464',
    projectId: 'vleague-ticket',
    authDomain: 'vleague-ticket.firebaseapp.com',
    storageBucket: 'vleague-ticket.appspot.com',
    measurementId: 'G-9SVKSPJ519',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2RPialBj-TTuJxCdDhz0nKr8ONiTjzho',
    appId: '1:79477247464:android:92d7acd90449d6f956a85d',
    messagingSenderId: '79477247464',
    projectId: 'vleague-ticket',
    storageBucket: 'vleague-ticket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSzmeOBX-iE8VYGIVFywgKchSllz7ZI-w',
    appId: '1:79477247464:ios:4cfdcb61b3d321eb56a85d',
    messagingSenderId: '79477247464',
    projectId: 'vleague-ticket',
    storageBucket: 'vleague-ticket.appspot.com',
    iosClientId: '79477247464-62e57jei3ra9r0js39cmigj1mgop4f2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.vleagueTicketV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSzmeOBX-iE8VYGIVFywgKchSllz7ZI-w',
    appId: '1:79477247464:ios:4cfdcb61b3d321eb56a85d',
    messagingSenderId: '79477247464',
    projectId: 'vleague-ticket',
    storageBucket: 'vleague-ticket.appspot.com',
    iosClientId: '79477247464-62e57jei3ra9r0js39cmigj1mgop4f2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.vleagueTicketV2',
  );
}
